In [7]:
import os
import subprocess
import pandas

In [8]:
# Path to root directory of the repo.
root_dir_ = subprocess.check_output(
    ["git", "rev-parse", "--show-toplevel"],
    text=True,
)
ROOT_DIR = root_dir_.strip()
# Path to data directory.
DATA_DIR = os.path.join(ROOT_DIR, "data")
# Path from which dataframe will be loaded
DF_PKL_PATH = os.path.join(DATA_DIR, "df.pkl")

In [9]:
df = pandas.read_pickle(DF_PKL_PATH)

In [10]:
df.sample(10)

,id,Age,pregnancies,bmi,insulin,glucose,bloodpressure,patientid,id,measurement_date,diabetespedigreefunction,outcome,patientid,id,skinthickness,patientid,id
1090,323,36,0,27.4,37,23,74,323,1091,2022-12-01,0.254,1,323,323,20,323,323
1128,361,29,5,31.2,80,92,99,361,1129,2022-12-01,0.583,1,361,361,33,361,361
711,712,40,5,29.6,22,126,78,712,712,2022-12-13,0.439,0,712,712,27,712,712
152,153,42,9,34.3,155,156,86,153,153,2022-12-13,1.189,1,153,153,28,153,153
786,19,33,1,43.3,50,162,25,19,787,2022-12-01,0.183,0,19,19,38,19,19
1199,432,38,3,30.4,15,7,75,432,1200,2022-12-01,0.551,0,432,432,16,432,432
206,207,57,8,37.5,280,196,76,207,207,2022-12-13,0.605,1,207,207,29,207,207
103,104,24,1,26.6,40,81,72,104,104,2022-12-13,0.283,0,104,104,18,104,104
331,332,25,2,32.7,52,87,58,332,332,2022-12-13,0.166,0,332,332,16,332,332
626,627,21,0,24.7,0,125,68,627,627,2022-12-13,0.206,0,627,627,0,627,627

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1536 entries, 0 to 1535
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        1536 non-null   int64
 1   Age                       1536 non-null   int64
 2   pregnancies               1536 non-null   int64
 3   bmi                       1536 non-null   float64
 4   insulin                   1536 non-null   int64
 5   glucose                   1536 non-null   int64
 6   bloodpressure             1536 non-null   int64
 7   patientid                 1536 non-null   int64
 8   id                        1536 non-null   int64
 9   measurement_date          1536 non-null   object
 10  diabetespedigreefunction  1536 non-null   float64
 11  outcome                   1536 non-null   int64
 12  patientid                 1536 non-null   int64
 13  id                        1536 non-null   int64
 14  skinthickness             1536 non-null   int64
 15  patientid                 1536 non-null   int64
 16  id                        1536 non-null   int64
dtypes: float64(2), int64(14), object(1)
memory usage: 204.1+ KB

ValueError: Grouper for 'patientid' not 1-dimensional